# spring cloud config server client.
spring:
  application:
    name: movie-info-service
  profiles:
    active: prod
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888