# spring cloud config server client.
spring:
  application:
    name: movie-info-service
  profiles:
    active: prod
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888




# custom props.
app:
  name: My App
  description: Welcome to ${spring.application.name}

my:
  greeting: Welcome to ${spring.application.name}
  list:
    values: one,two,three
  dbValues: "{url: 'http://oracledb', username: 'foo', password: 'foo'}"

db:
  connection: "http://oracledb"
  host: 127.0.0.1
  port: 1200