server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#      routes:

#        # Movie Catalog Service Route
#        - id: movie-catalog-route
#          predicates:
#            - Path=/movie-catalog-route/**
#          uri: lb://movie-catalog-service
#
#        # Movie Info Service Route
#        - id: movie-info-route
#          uri: lb://movie-info-service
#          predicates:
#            - Path=/movie-info-service/movies/**
#
#        # Ratings Data Service Route
#        - id: ratings-data-route
#          uri: lb://ratings-data-service
#          predicates:
#            - Path=/ratings-data-service/ratings/**

#        # Discovery Server Route
#        - id: discovery-server-route
#          uri: lb://localhost:8761
#          predicates:
#            - Path=/eureka/web
#          filters:
#            - SetPath=/