# spring cloud config server client.
spring:
  application:
    name: ratings-data-service
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888

# JPA & H2.
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    database: default
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:RatingsDB
    username: sa
    password:





# eureka client: not mandatory - this is the default for eureka.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082
