#
#spring:
#  application:
#    name: api-gateway
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#logging.level.root=INFO
#logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
#logging.level.org.springframework.cloud.gateway=TRACE
#
#
### Movie Catalog Service Route
#spring.cloud.gateway.routes[0].id=movie-catalog-service
#spring.cloud.gateway.routes[0].uri=lb://movie-catalog-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=**/api/movie-catalog/**
#
### Movie Info Service Route
#spring.cloud.gateway.routes[1].id=movie-info-service
#spring.cloud.gateway.routes[1].uri=lb://movie-info-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=**/api/movie-info/**
#
### Ratings Data Service Route
#spring.cloud.gateway.routes[2].id=ratings-data-service
#spring.cloud.gateway.routes[2].uri=lb://ratings-data-service
#spring.cloud.gateway.routes[2].predicates[0]=Path=**/api/ratings-data/**