server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
       git:
  #       uri: https://github.com/jeevanreddym/my-config-server-git-repo
          uri: "file:////C://Users//test//my-folder//Workspaces//my-config-server-git-repo"       # <--- local git repo.

