spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
#       git:
#         url: "https://github.com/jeevanreddym/my-springboot-cloud-workshop/tree/main/config-repo"
#        composite:
#          - type: native
#            search-locations: file:////C://Users//test//my-folder//Workspaces//config-repo # <--- local git repo.
        git:
          uri: "file:////C://Users//test//my-folder//Workspaces//config-repo"       # <--- local git repo.
server:
  port: 8888